{-
Created       : 2014 Mar 03 (Mon) 20:39:50 by Harold Carr.
Last Modified : 2014 May 17 (Sat) 11:24:39 by Harold Carr.
-}

{-# LANGUAGE TemplateHaskell #-}

module BitlyClientRequests
       ( Request(..)
       , makeRequestUrl -- this one is generated by BCTH
       )
       where

import           BitlyClientTH as BCTH

data Request
  = ExpandRequest { shortUrl :: [String] -- [URI]
                  , hash     :: [String]
                  }
  | InfoRequest { hash        :: [String]
                , shortUrl    :: [String] -- URI
                , expand_user :: Maybe Bool
                }
  | Link_SL_LookupRequest { url :: [String]
                          }
  | ShortenRequest { longUrl :: String
                   , domain  :: Maybe String
                   }
  | User_SL_Link_EditRequest { link     :: String
                             , title    :: Maybe String
                             , note     :: Maybe String
                             , private  :: Maybe Bool
                             , user_ts  :: Maybe Int
                             , archived :: Maybe Bool
                             , edit     :: [String]
                             }
  deriving (Eq, Show)

BCTH.mk ''Request

-- End of file.
